# SQLite version 3.x
#   gem install sqlite3
development:
  adapter: postgresql
  encoding: unicode
  database: botharetotallyenraged
  pool: 5 
  username: micahlinnemeier
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: botharetotallyenragedtest
  pool: 5
  username: micahlinnemeier
  password: